// <auto-generated />
namespace StoreAppTest.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LastChanges_19_09_2015_1600 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastChanges_19_09_2015_1600));
        
        string IMigrationMetadata.Id
        {
            get { return "201509191154135_LastChanges_19_09_2015_1600"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
