// <auto-generated />
namespace StoreAppTest.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TodayRefundIds_update_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TodayRefundIds_update_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201510150925349_TodayRefundIds_update_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
