// <auto-generated />
namespace StoreAppTest.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Something_03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Something_03));
        
        string IMigrationMetadata.Id
        {
            get { return "201510160422547_Something_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
